/**
 * sanitise-html — wraps sanitize-html with the project policy
 * applied to marked.parse() output before it reaches dangerouslySetInnerHTML.
 *
 * The upgrade page renders maintainer-controlled markdown (release notes
 * from the GitHub API and bundled manual-step descriptions). A compromised
 * upstream becomes XSS in every compositor instance unless the HTML is
 * sanitised between marked and React.
 *
 * Allowed tags cover the formatting that the existing release notes and
 * manual-step descriptions actually use: headings (with id attributes
 * generated by the custom Renderer at upgrade.tsx:209-212), paragraphs,
 * inline emphasis, anchors, code blocks, lists, blockquotes, images,
 * line and horizontal rules.
 *
 * Allowed URI schemes are restricted to http(s) and mailto via the
 * sanitize-html `allowedSchemes` option, with a per-tag override that
 * also permits `data:` for <img src> so embedded images in release
 * notes still render. The data:image/svg+xml rejection is enforced
 * via a `transformTags.img` hook that strips the `src` attribute when
 * the value matches `^data:image/svg+xml`, since sanitize-html's scheme
 * allowlist does not discriminate by data: MIME type on its own.
 */

import sanitizeHtml from "sanitize-html";

const ALLOWED_TAGS = [
  "h1", "h2", "h3", "h4", "h5", "h6",
  "p", "a", "code", "pre", "ul", "ol", "li",
  "strong", "em", "blockquote", "img", "br", "hr",
];

const ALLOWED_ATTRIBUTES = {
  "*": ["id", "class", "title", "alt"],
  a: ["href"],
  img: ["src", "alt"],
};

const ALLOWED_SCHEMES = ["http", "https", "mailto"];
const ALLOWED_SCHEMES_BY_TAG = {
  img: ["http", "https", "data"],
};

// Reject data:image/svg+xml on <img src> while allowing
// other data:image/* MIME types (png, jpeg, gif, webp, avif). The SVG
// attack surface (foreignObject, animation events, parser quirks) is
// closed by stripping the src attribute outright when the value matches.
//
// Normalise the value the way sanitize-html's downstream `naughtyHref`
// gate does — browsers ignore characters ≤ 0x20 when resolving URLs
// (OWASP XSS Filter Evasion Cheat Sheet — embedded tab), and HTML
// comments embedded mid-scheme can be used to fragment scheme detection.
// Without this normalisation, ` data:image/svg+xml`, `\tdata:...`,
// `&#x20;data:...`, and `da<!---->ta:image/svg+xml` all bypass the
// regex while still hitting the data: branch of the per-tag scheme
// allowlist downstream.
function rejectSvgDataUri(
  tagName: string,
  attribs: Record<string, string>,
): { tagName: string; attribs: Record<string, string> } {
  if (tagName === "img" && typeof attribs.src === "string") {
    let normalised = attribs.src.replace(/[\x00-\x20]+/g, "");
    while (true) {
      const start = normalised.indexOf("<!--");
      if (start === -1) break;
      const end = normalised.indexOf("-->", start + 4);
      if (end === -1) break;
      normalised = normalised.slice(0, start) + normalised.slice(end + 3);
    }
    if (/^data:image\/svg\+xml/i.test(normalised)) {
      const { src: _src, ...rest } = attribs;
      return { tagName, attribs: rest };
    }
  }
  return { tagName, attribs };
}

export function sanitiseHtml(html: string): string {
  return sanitizeHtml(html, {
    allowedTags: ALLOWED_TAGS,
    allowedAttributes: ALLOWED_ATTRIBUTES,
    allowedSchemes: ALLOWED_SCHEMES,
    allowedSchemesByTag: ALLOWED_SCHEMES_BY_TAG,
    allowedSchemesAppliedToAttributes: ["href", "src", "cite"],
    allowProtocolRelative: false,
    disallowedTagsMode: "discard",
    transformTags: { img: rejectSvgDataUri },
  });
}
