/**
 * sanitise-html — wraps isomorphic-dompurify with the project policy
 * applied to marked.parse() output before it reaches dangerouslySetInnerHTML.
 *
 * The upgrade page renders maintainer-controlled markdown (release notes
 * from the GitHub API and bundled manual-step descriptions). A compromised
 * upstream becomes XSS in every compositor instance unless the HTML is
 * sanitised between marked and React.
 *
 * Allowed tags cover the formatting that the existing release notes and
 * manual-step descriptions actually use: headings (with id attributes
 * generated by the custom Renderer at upgrade.tsx:209-212), paragraphs,
 * inline emphasis, anchors, code blocks, lists, blockquotes, images,
 * line and horizontal rules.
 *
 * Allowed URI schemes are restricted to http(s) and mailto via an
 * explicit ALLOWED_URI_REGEXP rather than DOMPurify's default (which
 * also permits tel: and ftp:). This keeps the policy auditable. For
 * <img> src specifically, DOMPurify's built-in handling permits
 * data:image/* independently of ALLOWED_URI_REGEXP — that is intentional
 * here so embedded images in release notes still render.
 */

import DOMPurify from "isomorphic-dompurify";

const ALLOWED_TAGS = [
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "p",
  "a",
  "code",
  "pre",
  "ul",
  "ol",
  "li",
  "strong",
  "em",
  "blockquote",
  "img",
  "br",
  "hr",
];

const ALLOWED_ATTR = ["id", "href", "src", "alt", "title", "class"];

// Restrict the URI scheme allowlist to http(s) and mailto so the policy is
// auditable. DOMPurify's default ALLOWED_URI_REGEXP also permits tel:, sms:,
// callto: and others; we narrow it explicitly. The pattern matches the
// scheme prefix at the start of the URL (DOMPurify tests the whole href/src
// against this regex). Same-document fragments like '#install' match the
// trailing alternation. Note: for <img> src, DOMPurify's built-in handling
// permits data:image/* independently of ALLOWED_URI_REGEXP.
const ALLOWED_URI_REGEXP = /^(?:(?:https?|mailto):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i;

export function sanitiseHtml(html: string): string {
  return DOMPurify.sanitize(html, {
    ALLOWED_TAGS,
    ALLOWED_ATTR,
    ALLOWED_URI_REGEXP,
    ALLOW_DATA_ATTR: false,
    USE_PROFILES: { html: true },
  });
}
