// @vitest-environment jsdom
/**
 * The step card's answer against what the site publishes. answer-preview.json
 * is written by answer-preview.py through the framework's own
 * `render_answer`; each case compares `renderAnswer`'s HTML, its kinds read
 * as the framework names them, its measure, whether it was cut and whether
 * the published answer is set in the smaller type.
 *
 * HTML is compared as parsed DOM with the whitespace between tags set aside,
 * so `<br />` and `<br>`, or `&rsquo;` and `’`, read alike. Differences the
 * preview accepts are recorded below as the exact output on both sides; a
 * new difference fails, and so does a recorded one that has changed or gone
 * away.
 *
 * The fixture is regenerated by `npm run parity:regenerate`. This file reads
 * only the committed fixture, so it runs without Python.
 *
 * @version v1.5.0-beta
 */
import { describe, expect, it } from "vitest";
import { renderAnswer, type AnswerKinds } from "~/lib/answer-preview";
import { ANSWER_BUDGET, BREAK_LINES, LINE_CHARS, MAX_PARAGRAPHS, SMALL_TYPE_LINES } from "~/lib/answer-budget";
import fixture from "./fixtures/answer-preview.json";

/** The framework's four kinds, in its order, and the Compositor's kinds each covers. */
const FRAMEWORK_KINDS: ReadonlyArray<[string, ReadonlyArray<keyof AnswerKinds>]> = [
  ["media", ["image", "embed"]],
  ["widgets", ["widget"]],
  ["footnotes", ["footnote"]],
  ["markup", ["table", "code_block", "rule", "heading", "list", "blockquote"]],
];

const frameworkKinds = (kinds: AnswerKinds) =>
  FRAMEWORK_KINDS.filter(([, ours]) => ours.some((kind) => kinds[kind] > 0)).map(([name]) => name);

/**
 * What the preview does not reproduce, both from the panel converter: `marked`
 * keeps the spaces before a hard break, which Python Markdown takes off, and
 * reads link text holding brackets one level deep, so a link whose text holds
 * a glossary reference is text in the preview and a link on the site (as in
 * card-markdown-parity's panels).
 */
const ACCEPTED: Record<string, { preview: string; site: string }> = {
  "a hard break": { preview: "<p>One <br> two</p>", site: "<p>One<br> two</p>" },
  "a glossary reference in a link's text": {
    preview:
      '<p>[see <a href="#" class="glossary-inline-link" data-term-id="IIIF" data-term-url="/telar/glossary/iiif/">International Image Interoperability Framework</a>](https://example.org/a) and <a href="#" class="glossary-inline-link" data-term-id="IIIF" data-term-url="/telar/glossary/iiif/">this</a>.</p>',
    site: '<p><a href="https://example.org/a">see International Image Interoperability Framework</a> and <a href="#" class="glossary-inline-link" data-term-id="IIIF" data-term-url="/telar/glossary/iiif/">this</a>.</p>',
  },
};

function parsedAnswerHtml(markup: string): string {
  const template = document.createElement("template");
  template.innerHTML = markup;
  const holder = document.createElement("div");
  holder.appendChild(template.content);
  return holder.innerHTML.replace(/>\s+</g, "><").replace(/\s+/g, " ").trim();
}

const glossary = { terms: new Map(Object.entries(fixture.glossary)), baseUrl: fixture.base_url };
const cases = fixture.cases.map((c) => [c.name, c] as const);

describe(`answers against framework ${fixture.framework_commit.slice(0, 8)}, Markdown ${fixture.markdown_version}`, () => {
  it("holds the budget the framework holds", () => {
    expect([fixture.budget, fixture.line_chars, fixture.break_lines, fixture.max_paragraphs, fixture.small_type_lines]).toEqual([
      ANSWER_BUDGET,
      LINE_CHARS,
      BREAK_LINES,
      MAX_PARAGRAPHS,
      SMALL_TYPE_LINES,
    ]);
  });

  it.each(cases)("HTML: %s", (name, c) => {
    const preview = parsedAnswerHtml(renderAnswer(c.source, glossary).html);
    const accepted = ACCEPTED[name];
    if (!accepted) {
      expect(preview).toBe(parsedAnswerHtml(c.html));
      return;
    }
    expect(preview).toBe(accepted.preview);
    expect(parsedAnswerHtml(c.html)).toBe(accepted.site);
  });

  it.each(cases)("kinds, measure, cut and type: %s", (_name, c) => {
    const rendered = renderAnswer(c.source, glossary);
    const { kinds, measure, cut, long } = rendered;
    expect({ kinds: frameworkKinds(kinds), measure, cut, long }).toEqual({
      kinds: c.kinds,
      measure: c.measure,
      cut: c.cut,
      long: c.long,
    });
  });

  it("records no difference for a case the corpus no longer holds", () => {
    const names = new Set(fixture.cases.map((c) => c.name));
    expect(Object.keys(ACCEPTED).filter((name) => !names.has(name))).toEqual([]);
  });
});
