"""
Writes app/lib/python-word-table.ts: the code points CPython's `\w` matches on
a `str` pattern, as inclusive ranges.

Run with the Python the framework's build pins (build.yml `python-version:
'3.11'`, Unicode 14.0):

    python3.11 scripts/generate-python-word-table.py > app/lib/python-word-table.ts

@version v1.5.0-beta
"""

import re
import sys
import unicodedata

word = re.compile(r"\w")
ranges = []
start = None
for cp in range(0x110000):
    hit = word.match(chr(cp)) is not None
    if hit and start is None:
        start = cp
    elif not hit and start is not None:
        ranges.append((start, cp - 1))
        start = None
if start is not None:
    ranges.append((start, 0x10FFFF))

py = ".".join(map(str, sys.version_info[:3]))
print("/**")
print(" * The code points CPython's `\\w` matches on a `str` pattern, as inclusive")
print(f" * ranges: Python {py}, Unicode {unicodedata.unidata_version}. Generated by")
print(" * scripts/generate-python-word-table.py; do not edit by hand.")
print(" *")
print(" * @version v1.5.0-beta")
print(" */")
print()
print(f'export const PYTHON_WORD_UNICODE_VERSION = "{unicodedata.unidata_version}";')
print()
print("export const PYTHON_WORD_RANGES: readonly (readonly [number, number])[] = [")
for a, b in ranges:
    print(f"  [0x{a:x}, 0x{b:x}],")
print("];")
